apiVersion: apps/v1
kind: Deployment
metadata:
  name: "vue-app-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "vue-app"
  template:
    metadata:
      labels:
        app: "vue-app"
    spec:
      containers:
        - name: "vue-app"
          image: "harrissonbiaggio94/vue-app"
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: vue-app-service
spec:
  selector:
    app: vue-app
  ports:
  - port: 8080
    name: http