version: '3.7'
services:
  nginx:
    build:
      dockerfile: ./nginx.dockerfile
      context: .
    image: webstore/nginx
    container_name: nginx
    ports:
      - "8000:80"
    networks:
      - network
    depends_on:
      - "monorepo"

  monorepo:
    build:
      dockerfile: ./dev.dockerfile
      context: .
    image: webstore/monorepo
    container_name: monorepo
    volumes:
      - ./packages/nextjs-blog/:/app/packages/nextjs-blog/
      - ./packages/react-app/:/app/packages/react-app/
      - ./packages/vue-app/:/app/packages/vue-app/
    ports:
      - "3000:3000"
      - "4000:4000"
      - "8080:8080"
    networks:
      - network


networks:
  network:
    driver: bridge
