apiVersion: apps/v1
kind: Deployment
metadata:
  name: "nextjs-blog-deployment"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "nextjs-blog"
  template:
    metadata:
      labels:
        app: "nextjs-blog"
    spec:
      containers:
        - name: "nextjs-blog"
          image: "harrissonbiaggio94/nextjs-blog"
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: nextjs-blog-service
spec:
  selector:
    app: nextjs-blog
  ports:
  - port: 80
    targetPort: 3000
    name: http