apiVersion: apps/v1
kind: Deployment
metadata:
  name: "nextjs-blog-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "nextjs-blog"
  template:
    metadata:
      labels:
        app: "nextjs-blog"
    spec:
      containers:
        - name: "nextjs-blog"
          image: "harrissonbiaggio94/nextjs-blog"
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nextjs-blog-service
spec:
  ports:
    - port: 80
      name: http-web
  type: ClusterIP
  selector:
    app: nextjs-blog